### ISSUE TITLE
Incorrect link

### ISSUE THREAD

**Issue by benkoshy** [merciremi/remicodes#2]
https://remimercier.com/pry-byebug-intermediate/#fn:1

I think it is high time we dive deeper into pry-byebug. Are you new to pry-byebug? Go and check the beginners introduction to debugging your code first < ------ this link is not working.

![image](https://user-images.githubusercontent.com/15097447/104967658-01374580-5a38-11eb-8d43-c7b3fa289d86.png)

**Comment by merciremi** [comment]
Hey @benkoshy, sorry I'm getting back to you mooonths after your issue. I had disabled Github notifications 😅 . 

Thanks a lot for pointing that out, it's fixed now. 🙏
