### ISSUE TITLE
Glitch about `let` expressions caching in "RSpec fundamentals: a basic glossary" article

### ISSUE THREAD

**Issue by cgrothaus** [merciremi/remicodes#3]
Hi Rémi, 

in your article ["RSpec fundamentals: a basic glossary"](https://remimercier.com/rspec-fundamentals-glossary/) there is a glitch about `let` epxressions caching/memoizing behaviour. You write the "value is cached across the example group", but per the RSpec docs it is ["cached across multiple calls in the same example but not across examples"](https://relishapp.com/rspec/rspec-core/v/3-10/docs/helper-methods/let-and-let).

Regards
Christoph

**Comment by merciremi** [comment]
Hey @cgrothaus, sorry for getting back to you so late. Good catch, my English is to blame on this one. I used `across` as `for all examples within the scope of the example group where the let is defined.`

Will fix this.
